riddles = [
    ("Tiene famosa memoria, gran tamaño y dura piel y la nariz más grandota, que en el mundo pueda haber.", "el elefante"),
    ("En rincones y entre ramas mis redes voy construyendo, para que moscas incautas, en ellas vayan cayendo.", "la araña"),
    ("Camino sin tener patas, a cuestas llevo mi casa. Por donde mi cuerpo pasa queda un hilillo de plata.", "el caracol"),
    ("¿Quién allá en lo alto en las ramas mora y allí esconde, avara, todo lo que roba?", "la ardilla"),
    ("Por un caminito, va caminando un bicho. El nombre del bicho ya te lo he dicho.", "la vaca"),
    ("Orejas largas, rabo cortito, corro y salto muy ligerito.", "el conejo"),
    ("No lo parezco y soy pez, y mi forma la refleja una pieza de ajedrez.", "el caballito de mar"),
    ("Si me escribes como es, soy de la selva el rey, si me escribes al revés, yo seré Papá Noel.", "el leon"),
    ("Es la reina de los mares, su dentadura es muy buena, y por no ir nunca vacía, siempre dicen que va llena.", "la ballena"),
    ("Tengo orejas largas y una cola diminuta. Si echamos una carrera, gano sin disputa.", "el conejo"),
    ("Blanca por dentro, verde por fuera, si quieres que te lo diga, espera.", "la pera"),
    ("Soy ave y soy llana, pero no tengo pico ni alas.", "la avellana"),
    ("Te lo digo y te repito y te lo debo avisar que por más que te lo diga no lo vas a adivinar.", "el te"),
    ("Su interior es blanco y dulce. Por fuera peludo y feo. Su nombre asusta a los niños, pero a mí no me da miedo.", "el coco"),
    ("Soy un viejo arrugadito que si me echan al agua me pongo gordito.", "el garbanzo"),
    ("Oro parece, plata no es, quien no lo adivine, muy tonto es.", "el platano"),
    ("Soy verde por fuera, roja por dentro, y muchas semillas tengo. ¿Qué soy?", "la sandia"),
    ("Soy pequeña, redonda y dulce, y vengo en racimos. ¿Qué soy?", "la uva"),
    ("En el bosque me encontrarás, roja y jugosa soy. Blancos lunares llevo y mermelada me harán. ¿Qué soy?", "la fresa"),
    ("En la huerta me verás, con hojas y raíz. Soy de color naranja y mi sabor te hará feliz. ¿Qué soy?", "la zanahoria"),
    ("Soy amarillo y curvado, y si me pelas, mi interior encontrarás jugoso. ¿Qué soy?", "el platano"),
    ("Suena a la misma hora todas las mañanas, para decirnos a todos: ¡Fuera de la cama!", "el despertador"),
    ("Ruedo, ruedo y en los bolsillos me quedo.", "la moneda"),
    ("Tiene luna, no es planeta; tiene marco y no es puerta.", "el espejo"),
    ("Tengo copa y no soy árbol, tengo alas y no soy pájaro; protejo del sol a mi amo en invierno y en verano.", "el sombrero"),
    ("Me llegan las cartas y no sé leer y, aunque me las trago, no mancho el papel. ¿Qué es?", "el buzon"),
    ("Todos me quieren para descansar. ?No lo sabes? ¡Si ya te lo he dicho! No lo pienses más.", "la silla"),
    ("Es pequeña como una pera, pero alumbra la casa entera. ¿Qué es?", "la bombilla"),
    ("Lana sube, lana baja ¿Qué es?", "la navaja"),
    ("Tengo agujas, pero no puedo coser. Tengo números, pero no puedo contar. ¿Qué soy?", "el reloj"),
    ("Soy redondo como una pelota, pero no puedo botar. Me pones en tu cabeza cuando hace sol. ¿Qué soy?", "el sombrero"),
    ("Soy brillante como el sol, pero no puedo dar calor. Me usas para iluminar una habitación. ¿Qué soy?", "la lampara"),
    ("Soy plano y rectangular, con muchas páginas en mi interior. Me usas para escribir historias y dibujar. ¿Qué soy?", "el cuaderno"),
    ("Tengo teclas, pero no puedo tocar música. Tengo letras, pero no puedo hablar. ¿Qué soy?", "el teclado"),
    ("Todo el mundo lo lleva, todo el mundo lo tiene, porque a todos les dan uno en cuanto al mundo vienen.", "el nombre"),
    ("Se parece a mi madre pero es más mayor, tiene otros hijos que mis tíos son.", "la abuela"),
    ("¿A qué reyes me refiero, que a Belén fueron guiados por una estrella de Oriente, llevando oro y presentes y encontraron a otro Rey, recién nacido en el suelo? ¿A qué reyes me refiero?", "los reyes magos"),
    ("Entre la lluvia y el sol, un arco a todo color.", "el arcoiris"),
    ("Con una manguera, casco y escalera apago los fuegos y las hogueras.", "el bombero"),
    ("Si dices mi nombre se rompe.", "el silencio"),
    ("Me pones y me quitas, me tomas y me dejas, conmigo no tiritas y estoy hecho de madejas.", "el jersey"),
    ("Si me lanzas al cielo, vuelo sin alas. Si me mojas, me derrito. ¿Qué soy?", "el hielo"),
]
